### ISSUE TITLE
v3.0.0-beta01: FSharp.Formatting.Razor.dll is not in the package

### ISSUE THREAD

**Issue by et1975** [fsprojects/FSharp.Formatting#438]
Living on the edge... trying to use your generate.fsx with the beta.

**Comment by jackfoxy** [comment]
I solved this by changing line 5
// #r "../Microsoft.AspNet.Razor/lib/net45/System.Web.Razor.dll"
#r "System.Web.Razor.dll"

**Comment by matthid** [comment]
I guess this is solved?

**Comment by et1975** [comment]
I haven't tried migrating my docs to netcore again, so can't confirm.

**Comment by et1975** [comment]
@matthid I think this needs to be reopened.

@jackfoxy how do you fix this?
https://github.com/fsprojects/FSharp.Formatting/blob/master/packages/FSharp.Formatting/FSharp.Formatting.fsx#L5-L16
still includes files in a way that assumes local "packages" folder, which simply doesn't work if you use it from FAKE5 or with `storage: none`.

**Comment by matthid** [comment]
So we should include a relative path which works in the NuGet cache as well? But that hasn't anything to do with v3 as the title indicates?

**Comment by et1975** [comment]
I can see that the lib is now included in the package, but since the script is still not referring to it hasn't really been fixed.
The fix would have been kind pointless in my case considering the next few lines, so I dunno... you want me to open another issue?

**Comment by matthid** [comment]
No I just try to understand what's going on

**Comment by matthid** [comment]
Can you please change the title such that it represents the issue accordingly?

**Comment by et1975** [comment]
Let's close this, there's just too much to get it working the way I want.

**Comment by jackfoxy** [comment]
@et1975  checkout  https://github.com/fsprojects/ProjectScaffold or my personal fork of ProjectScaffold. I have F#.Formatting 3.1 working from the build program there, If you have a problem open an issue. (Never tested outside of Windows, so far as I know.)
